### PR TITLE
Improve command captions

### LINKED ISSUE #27: 'Delete favorite' command should be reworded 'Remove from Favorites'
image

Changing the text to 'Remove from Favorites' aligns it better with the 'Add to Favorites' entry on Explorer context menu.

Also, 'Remove' is a less alarming word than 'Delete' IMO.

### PR DESCRIPTION
**Pull request by gjsjohnmurray**
This PR fixes #27.

As well as rewording the English caption for `command.favorites.deletefavorite` I also standardized capitalization on two other commands.

### CODE REVIEW

**Comment by leftstick** [comment]
@gjsjohnmurray please fix conflict. 
 i will merge then, Thanks

**Comment by gjsjohnmurray** [comment]
@leftstick I have now added your new `command.favorites.revealInSiderbar` line to my branch and pushed. I think you can safely accept my package.nls.json now.

After you have merged this, maybe consider changing your new command id to be `command.favorites.revealInSidebar` instead of `command.favorites.revealInSide**r**bar`

**Comment by leftstick** [comment]
no. cannot. Github won't accept mr if conflict exists. 
you cannot just commit something directly in your fork.
You have to sync your fork with my latest update, solve the conflict, then commit your fix. this is merge request rule we must follow.

**Comment by gjsjohnmurray** [comment]
OK thanks. I think I've done the right thing now.

**Pull request merged**
